To Do List Crud
akbarsazish/To-Do-List pull request #3
Opened 2023-06-22 22:19 UTC by akbarsazish

0- Configure linters.
1- Set up a new project with webpack.
2-  Create an index.html.
3- Creat module folder and added two files form.js and todos.js
4- Create an index.js file and set an array of some simple to do tasks (array of objects)
5- Each task object  contain three keys: a- description [string]. b- completed [bool]. c- index: [number].
6- Create a style.css and set rules for the To Do List.
7- In this project you can add items, edit items and remove it.

2023-06-22 22:26 UTC, 1GORDON reviewed
##
## Hi @akbarsazish ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Kindly remove the live demo section from your readme file since this project is not deployed. This is a general requirement for all projects.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 23:11 UTC, Ismailco requested changes
### Hi @akbarsazish, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 23:11 UTC, Ismailco commented on src/modules/form.js
> +form.addEventListener('keydown', (event) => {
- [ ] When adding a new task to the list the index should start from `1` in the local storage not `0`, kindly make sure to fix this issue so the app works as expected

![Screenshot_20230623_000139](https://github.com/akbarsazish/To-Do-List/assets/25227022/f56fb3f5-d6fb-412c-be5e-d1e02eded37e)

2023-06-22 23:11 UTC, Ismailco commented on src/modules/form.js
> +const removeTodo = (index) => { // eslint-disable-line
- [ ] When removing a task from the list the index should replace the old removed task, kindly consider fixing this so all the indexes are displayed correctly

![Screenshot_20230623_000204](https://github.com/akbarsazish/To-Do-List/assets/25227022/86b9e7e1-560d-4ba1-99a7-d689f1a1c79e)

2023-06-22 23:11 UTC, Ismailco commented on src/modules/form.js
> +todosListParent.addEventListener('click', (e) => {
- [ ] The edit is not working properly, when I click on the edit button it throws this error in the browser, kindly make sure to fix this so users can modify the tasks

![Screenshot_20230623_000423](https://github.com/akbarsazish/To-Do-List/assets/25227022/ff90f394-a6be-4c9a-b64c-554c7121d1a0)

2023-06-23 08:14 UTC, binhussen approved these changes
Hi @akbarsazish , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Works add, edit & remove✔️
- Well structured Code ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 15:00 UTC, merged